[[plugins]]
repo = 'Shougo/neocomplete'
on_i = 1

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add ='''
#    autocmd FileType python setlocal completeopt-=preview
#    let g:jedi#popup_on_dot = 0
#'''
