[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nmap <C-k> <Plug>(caw:hatpos:toggle)
vmap <C-k> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
let g:EasyMotion_leader_key=","
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add ='''
    let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
