[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
let g:EasyMotion_leader_key=","
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-surround'

